### ISSUE TITLE
HOW TO COMPILE?

### ISSUE THREAD

**Issue by Porama6400** [Cactose/Grappl#11]
HOW TO COMPILE?
i want to compile grappl relay server but how?

**Comment by Porama6400** [comment]
what software do you use?

**Comment by Cactose** [comment]
I use Intellij idea with javac. You should be able to compile this fine with just javac, though

**Comment by Porama6400** [comment]
now i can compile it but i got this error when run

D:\Users\Porama6400>java -jar D:\Users\Porama2\Desktop\GrapplRelay.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/Gson
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

**Comment by Cactose** [comment]
You need the Gson 2.2.4 .jar in the same directory as GrapplRelay.jar

http://mvnrepository.com/artifact/com.google.code.gson/gson/2.2.4

**Comment by Porama6400** [comment]
thanks a lot
